#!/usr/bin/env node
'use strict'

const argv = require('./lib/command-line-args')
const loadKeymapFromFile = require('./lib/keymap-loader')

const kleSoureceFilename = argv._[0]
const keymap = loadKeymapFromFile(kleSoureceFilename)
const { layerPlan } = require('./lib/layer-plans')
const logger = require('./lib/logger')
const config = require('./lib/config')

function main() {
  if (argv.verbose)
    logger.setLogLevelByName("debug")

  if (argv.configFile) {
    config.loadConfigurationFile(argv.configFile)
    if (argv.section != undefined)
      config.loadConfigurationProfile('sections', argv.section)

    config.loadConfigurationProfile('layers', argv.layer)

    if (argv.operation)
      config.loadConfigurationProfile('operations', argv.operation)

  }

  logger.debug('Current dimensions:')
  logger.debug(config.dimensions)

  return layerPlan(keymap, argv)
}

require('./lib/render/svg-output')(main, kleSoureceFilename, argv)
