#!/usr/bin/env node
'use strict'

const argv = require('./lib/command-line-args')
const config = require('./lib/config')
const loadKeymapFromFile = require('./lib/keymap-loader')

const kleSoureceFilename = argv._[0]
const keymap = loadKeymapFromFile(kleSoureceFilename)
const { layerPlan } = require('./lib/layer-plans')
const logger = require('./lib/logger')

function main() {
  if (argv.verbose)
    logger.setLogLevelByName("debug")

  config.loadConfiguration(argv)

  logger.debug('Config.dimensions:')
  logger.debug(config.dimensions)

  return layerPlan(keymap, argv)
}

require('./lib/render/svg-output')(main, kleSoureceFilename, argv)
