#!/usr/bin/env node
'use strict'

const fatalError = require('./lib/fatal-error')
const argv = require('./lib/command-line-args')
const loadKeymapFromFile = require('./lib/keymap-loader')

const kleSoureceFilename = argv._[0]
const keymap = loadKeymapFromFile(kleSoureceFilename)
const { layerPlan } = require('./lib/layer-plans')
const config = require('./lib/config')

function main() {
  if (argv.configFile) {
    config.loadConfigurationFile(argv.configFile)
    console.log(config.layers)
  }
  return layerPlan(keymap, argv)
}

require('./lib/render/svg-output')(main, kleSoureceFilename + ".svg", argv)
